/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ExcluirContaRouteImport } from './routes/excluir-conta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CThreadIdRouteImport } from './routes/c.$threadId'
import { Route as ApiModelosRouteImport } from './routes/api/modelos'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAccountRouteImport } from './routes/api/account'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcluirContaRoute = ExcluirContaRouteImport.update({
  id: '/excluir-conta',
  path: '/excluir-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CThreadIdRoute = CThreadIdRouteImport.update({
  id: '/c/$threadId',
  path: '/c/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelosRoute = ApiModelosRouteImport.update({
  id: '/api/modelos',
  path: '/api/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/api/modelos': typeof ApiModelosRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/api/modelos': typeof ApiModelosRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/api/modelos': typeof ApiModelosRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/excluir-conta'
    | '/sitemap.xml'
    | '/api/account'
    | '/api/chat'
    | '/api/modelos'
    | '/c/$threadId'
    | '/api/auth/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/excluir-conta'
    | '/sitemap.xml'
    | '/api/account'
    | '/api/chat'
    | '/api/modelos'
    | '/c/$threadId'
    | '/api/auth/profile'
  id:
    | '__root__'
    | '/'
    | '/excluir-conta'
    | '/sitemap.xml'
    | '/api/account'
    | '/api/chat'
    | '/api/modelos'
    | '/c/$threadId'
    | '/api/auth/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExcluirContaRoute: typeof ExcluirContaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiModelosRoute: typeof ApiModelosRoute
  CThreadIdRoute: typeof CThreadIdRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excluir-conta': {
      id: '/excluir-conta'
      path: '/excluir-conta'
      fullPath: '/excluir-conta'
      preLoaderRoute: typeof ExcluirContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$threadId': {
      id: '/c/$threadId'
      path: '/c/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof CThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modelos': {
      id: '/api/modelos'
      path: '/api/modelos'
      fullPath: '/api/modelos'
      preLoaderRoute: typeof ApiModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExcluirContaRoute: ExcluirContaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiChatRoute: ApiChatRoute,
  ApiModelosRoute: ApiModelosRoute,
  CThreadIdRoute: CThreadIdRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
